# Generated by Django 5.2.5 on 2025-08-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udyam_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AadhaarVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrepreneur_name', models.CharField(max_length=255)),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('otp', models.CharField(max_length=6)),
                ('consent_given', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UdyamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar', models.CharField(max_length=12)),
                ('otp', models.CharField(max_length=6)),
                ('pan', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
