# Generated by Django 5.2.5 on 2025-08-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udyam_app', '0002_aadhaarverification_udyamregistration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aadhaarverification',
            old_name='aadhaar_number',
            new_name='aadhaar',
        ),
        migrations.RemoveField(
            model_name='aadhaarverification',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='aadhaarverification',
            name='otp',
        ),
        migrations.AlterField(
            model_name='aadhaarverification',
            name='entrepreneur_name',
            field=models.CharField(max_length=100),
        ),
    ]
